my:
  config:
    key: ${WEB4_CONFIG_KEY}


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/web3
    password: s409331
    username: s409331
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: false
  mail:
    host: smtp.yandex.ru
    port: 587
    username: ${WEB4_EMAIL}
    password: ${WEB4_EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true



